[package]
name = "cita_cloud_proto"
version = "6.3.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2018"
license = "Apache-2.0"
description = "cita-cloud proto library"


[dependencies]
tonic = "0.5.0"
prost = "0.8.0"
tokio = { version = "1.9.0", features = ["full"] }

[build-dependencies]
tonic-build = "0.5.1"
