[package]
name = "cita_cloud_proto"
version = "6.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2018"

[dependencies]
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }

[build-dependencies]
tonic-build = "*"
