[package]
name = "cita_cloud_proto"
version = "5.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2018"

[dependencies]
tonic = "0.4.3"
prost = "0.7.0"
tokio = { version = "1.5.0", features = ["full"] }

[build-dependencies]
tonic-build = "0.4.2"
