[package]
name = "cita_cloud_proto"
version = "6.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2018"

[dependencies]
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
tonic-build = "0.5"
