[package]
name = "cita_cloud_proto"
version = "6.2.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2018"

[dependencies]
tonic = "0.5.0"
prost = "0.8.0"
tokio = { version = "1.8", features = ["full"] }

[build-dependencies]
tonic-build = "0.5.1"
