[package]
name = "cita_cloud_proto"
version = "0.1.0"
authors = ["rink1969 <rink1969@gmail.com>"]
edition = "2018"

[dependencies]
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }

[build-dependencies]
tonic-build = "*"
