// Copyright Rivtower Technologies LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package blockchain;

message BlockHeader {
    // hash of previous BlockHeader
    bytes prevhash = 1;
    // unit: Millisecond
    uint64 timestamp = 2;
    uint64 height = 3;
    // root hash of transaction list
    bytes transactions_root = 4;
    // address of validator who propose current block
    bytes proposer = 5;
}

message Transaction {
    // version == sys_config.version
    uint32 version = 1;
    // length(to) == 20
    bytes to = 2;
    // length(nonce) <= 128
    string nonce = 3;
    // quota <= sys_config.quota_limit
    uint64 quota = 4;
    // current_block_number < valid_until_block <= current_block_number + sys_config.block_limit
    uint64 valid_until_block = 5;
    bytes data = 6;
    // length(value) == 32
    bytes value = 7;
    // length(chain_id) == 32 and chain_id == sys_config.chain_id
    bytes chain_id = 8;
}

message Witness {
    bytes signature = 1;
    // cita-cloud does not fix a specific address algorithm
    // the sender may not be recoverable from the signature
    // Therefore, this field is added separately.
    bytes sender = 2;
}

message UnverifiedTransaction {
    Transaction transaction = 1;
    // cita-cloud does not fix a specific hash algorithm
    // Therefore, this field is added separately.
    bytes transaction_hash = 2;
    Witness witness = 3;
}

message UtxoTransaction {
    // version == sys_config.version
    uint32 version = 1;
    bytes pre_tx_hash = 2;
    bytes output = 3;
    // in a lock_id range define by controller
    uint64 lock_id = 4;
}

message UnverifiedUtxoTransaction {
    UtxoTransaction transaction = 1;
    // cita-cloud does not fix a specific hash algorithm
    // Therefore, this field is added separately.
    bytes transaction_hash = 2;
    repeated Witness witnesses = 3;
}

message RawTransaction {
    oneof tx {
        UnverifiedTransaction normal_tx = 1;
        UnverifiedUtxoTransaction utxo_tx = 2;
    }
}

message RawTransactions {
    repeated RawTransaction body = 1;
}

message CompactBlockBody {
    // transaction hash of UnverifiedTransaction or UnverifyedUtxoTransaction.
    repeated bytes tx_hashes = 1;
}

message CompactBlock {
    // for now it's always 0
    uint32 version = 1;
    BlockHeader header = 2;
    CompactBlockBody body = 3;
}

message Block {
    // for now it's always 0
    uint32 version = 1;
    BlockHeader header = 2;
    RawTransactions body = 3;
    // block valid proof generated by consensus
    bytes proof = 4;
    // root hash of world state after exec current block
    // generated by executor
    bytes state_root = 5;
}
